name: Package Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php-versions: ['7.3']
        laravel-versions: ['5.8', '6.0']

    name: PHP ${{ matrix.php-versions }} / Laravel ${{ matrix.laravel-versions }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2
  
    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        tools: composer

    - name: Validate composer setup
      run: composer validate

    - name: Install Laravel
      run: composer require "laravel/framework:${{ matrix.laravel-versions }}" --no-update

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate code style
      run: |
        composer require "squizlabs/php_codesniffer=*" --no-update
        bin/phpcs --standard="phpcs.xml" .

    - name: Run test suite
      run: composer run-script test

    - name: Upload coverage results
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer require cedx/coveralls --no-update
        bin/coveralls build/logs/clover.xml
