name: Package Test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      max-parallel: 3
      matrix:
        php: ['7.2', '7.3', '7.4']
        laravel: ['5.8', '6.0', '7.0', '8.0']
        include:
            - laravel: 8.0
              testbench: 6.*
              legacy: "laravel/legacy-factories:^1.0.4"
            - laravel: 7.0
              testbench: 5.*
            - laravel: 6.0
              testbench: 4.*
            - laravel: 5.8
              testbench: 3.8.*
        exclude:
            - php: 7.4
              laravel: 5.8
            - php: 7.2
              laravel: 8.0

    name: PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v1
      with:
        php-version: ${{ matrix.php }}
        coverage: xdebug
        tools: composer

    - name: Validate composer setup
      run: composer validate --strict

    - name: Install Laravel and Orechestra Testbench
      run: composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" ${{ matrix.legacy }} --no-interaction --no-update

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Normalize composer file
      run: composer normalize --dry-run

    - name: Validate code style
      run: |
        composer require "squizlabs/php_codesniffer=*"
        bin/phpcs --standard="phpcs.xml" .

    - name: Run test suite
      run: composer run-script test

    - name: Upload coverage results
      if: matrix.php == '7.4' && matrix.laravel == '7.0'
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer require cedx/coveralls
        bin/coveralls build/logs/clover.xml
